// src/pages/status.js
import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import "../styles/NoCodeBench.css";

const TASK_ID = 2; // 先寫死，之後可以從路由或 props 傳進來

// 很簡單的 unified diff renderer：用每一行的第一個字元決定顏色
const DiffViewer = ({ patch }) => {
  if (!patch || patch.trim() === "") {
    return (
      <div className="diff-viewer">
        <div className="diff-header">Generated patch</div>
        <div className="diff-empty">No patch generated.</div>
      </div>
    );
  }

  const lines = patch.split("\n");

  return (
    <div className="diff-viewer">
      <div className="diff-header">Generated patch</div>
      <div className="diff-code">
        {lines.map((line, idx) => {
          let type = "context";
          if (line.startsWith("diff --git")) type = "file";
          else if (line.startsWith("@@")) type = "hunk";
          else if (line.startsWith("+") && !line.startsWith("+++")) type = "add";
          else if (line.startsWith("-") && !line.startsWith("---")) type = "del";
          else if (
            line.startsWith("index ") ||
            line.startsWith("--- ") ||
            line.startsWith("+++ ")
          ) {
            type = "meta";
          }

          const prefix = line[0] || " ";
          const content = line.slice(1);

          return (
            <pre key={idx} className={`diff-line diff-${type}`}>
              <span className="diff-prefix">{prefix}</span>
              <span className="diff-text">{content}</span>
            </pre>
          );
        })}
      </div>
    </div>
  );
};

const StatusAnalytics = () => {
  const navigate = useNavigate();

  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [task, setTask] = useState(null);

  useEffect(() => {
    const fetchTask = async () => {
      try {
        setLoading(true);
        setError("");

        const res = await fetch(
          `http://localhost:3001/tasks/${TASK_ID}`
        );// `http://127.0.0.1:3001/api/tasks/${TASK_ID}/`
        if (!res.ok) {
          throw new Error(`Request failed: ${res.status}`);
        }
        const data = await res.json();
        setTask(data);
      } catch (err) {
        console.error(err);
        setError("Failed to load task status.");
      } finally {
        setLoading(false);
      }
    };

    fetchTask();
  }, []);

  const result = task?.result || {};
  const generatedPatch = result.generated_patch || "";
  const statusText = task?.status || "UNKNOWN";

  return (
    <div className="page status-page">
      <div className="nebula nebula-1" />
      <div className="nebula nebula-2" />

      <div className="glass-card status-card">
        <header className="status-header">
          <div>
            <p className="breadcrumb"></p>
            <h2 className="status-title">Generated Edits &amp; Evaluation Results</h2>
            <p className="status-subtitle">
              The left panel shows the patch generated by the agent. On the
              right you&apos;ll find a compact summary of test results and
              metrics.
            </p>
          </div>
          <div className="choose-chip">Final Step · Evaluation & analysis</div>
        </header>

        {loading ? (
          <p className="status-loading">Loading task status…</p>
        ) : error ? (
          <p className="status-error">{error}</p>
        ) : (
          <div className="status-layout">
            {/* 左邊：Patch / Repository overview */}
            <section className="status-section">
              <h3 className="status-section-title">Code Modifications</h3>

              <div className="status-block">
                <div className="status-row">
                  <span className="status-label">NoCode-bench ID</span>
                  <span className="status-value">
                    {task?.nocode_bench_id || "—"}
                  </span>
                </div>
                <div className="status-row">
                  <span className="status-label">Status</span>
                  <span className="status-value">{statusText}</span>
                </div>
                <div className="status-row">
                  <span className="status-label">Tokens</span>
                  <span className="status-value">
                    {result.num_token ?? "—"}
                  </span>
                </div>
                <div className="status-row">
                  <span className="status-label">Run time (s)</span>
                  <span className="status-value">
                    {result.run_time_seconds?.toFixed
                      ? result.run_time_seconds.toFixed(1)
                      : result.run_time_seconds ?? "—"}
                  </span>
                </div>
              </div>

              {/* 這裡就是 GitHub 風格 diff viewer */}
              <DiffViewer patch={generatedPatch} />
            </section>

            {/* 右邊：Status Results / metrics */}
            <section className="status-section">
              <h3 className="status-section-title">Evaluation &amp; Quality Metrics</h3>
              <div className="status-block">
                <div className="status-kpis">
                  <div className="status-kpi">
                    <span className="status-kpi-label">Overall status</span>
                    <span className="status-kpi-value status-kpi-pass">
                      {statusText}
                    </span>
                    <span className="status-kpi-desc">
                      f2p: {result.f2p_passed_count ?? 0} /{" "}
                      {result.f2p_total_count ?? 0}
                    </span>
                  </div>
                  <div className="status-kpi">
                    <span className="status-kpi-label">Applied %</span>
                    <span className="status-kpi-value">
                      {(result.applied_percent ?? 0).toFixed
                        ? result.applied_percent.toFixed(1)
                        : result.applied_percent ?? 0}
                      %
                    </span>
                    <span className="status-kpi-desc">
                      How much of the patch was applied.
                    </span>
                  </div>
                  <div className="status-kpi">
                    <span className="status-kpi-label">File coverage %</span>
                    <span className="status-kpi-value">
                      {(result.file_percent ?? 0).toFixed
                        ? result.file_percent.toFixed(1)
                        : result.file_percent ?? 0}
                      %
                    </span>
                    <span className="status-kpi-desc">
                      Share of files that matched the ground truth.
                    </span>
                  </div>
                </div>

                <div className="status-log">
                  <p className="status-log-label">Doc change input</p>
                  <ul className="status-log-list">
                    <li>{task?.doc_change_input || "—"}</li>
                  </ul>
                </div>
              </div>
            </section>
          </div>
        )}

        <footer className="status-footer">
          <button className="btn btn-secondary" onClick={() => navigate("/")}>
            <span className="btn-main-text">Exit Evaluation</span>
            <span className="btn-sub-text">Back to home page</span>
          </button>
        </footer>
      </div>
    </div>
  );
};

export default StatusAnalytics;